Mediforbidden/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', include('searchmed.urls')),
    path('admin/', admin.site.urls),
    path('login/', auth_views.LoginView.as_view(template_name='searchmed/login.html'), name='login'),
]

searchmed/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from .views import CustomLoginView

app_name = 'searchmed'

urlpatterns = [
    path('', views.home_view, name='home'),
    path('combine/', views.combine_view, name='combine'),
    path('add_med_user/', views.add_med_user_view, name='add_med_user'),
    path('check_medicine/', views.check_medicine, name='check_medicine'),
    path('check_contraindication/', views.check_contraindication, name='check_contraindication'),
    path('get_user_medications/', views.get_user_medications, name='get_user_medications'),
    path('addinfo/', views.addinfo_view, name='addinfo'),
    path('signup/', views.signup_view, name='signup'),
    path('logout/', auth_views.LogoutView.as_view(next_page='searchmed:home'), name='logout'),
    path('login/', CustomLoginView.as_view(), name='login'),
    path('user_med/', views.user_med_view, name='user_med'),
    path('add_medicine/', views.add_medicine, name='add_medicine'),
    path('get_user_contraindications/', views.get_user_contraindications, name='get_user_contraindications'),
    #path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
]

searchmed/models.py
from django.db import models
from django.contrib.auth.models import User

class Med(models.Model):
    id = models.AutoField(primary_key=True)
    compound_name = models.CharField(max_length=225, blank=True, null=True)
    compound_code = models.CharField(max_length=225, blank=True, null=True)
    product_code = models.IntegerField(blank=True, null=True)
    product_name = models.CharField(max_length=225, blank=True, null=True)
    company_name = models.CharField(max_length=225, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'med'


class Medcontraindication(models.Model):
    med_id_a = models.ForeignKey(Med, models.DO_NOTHING, db_column='med_id_a', blank=True, null=True)
    med_id_b = models.ForeignKey(Med, models.DO_NOTHING, db_column='med_id_b', related_name='medcontraindication_med_id_b_set', blank=True, null=True)
    contraindicated_info = models.CharField(max_length=225, blank=True, null=True)
    notification_no = models.CharField(max_length=50, blank=True, null=True)
    notification_date = models.DateField(blank=True, null=True)
    detail_info = models.CharField(max_length=255, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'medcontraindication'

class UserMedication(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    med = models.ForeignKey(Med, on_delete=models.CASCADE)

searchmed/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse
from django.http import HttpResponse, HttpResponseForbidden
from .models import Med, Medcontraindication, UserMedication
from django.contrib.auth.decorators import login_required
from django.db.models import Q
import ctypes
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login
from django.contrib.auth.views import LoginView
from django.urls import reverse_lazy
import numpy as np

# Load the shared library
med_db_lib = ctypes.CDLL('./libs/med_db.so')

# Create your views here.
def home_view(request) :
	return render(request, 'searchmed/home.html', {})

def combine_view(request) :
    return render(request, 'searchmed/combine.html', {})

def add_med_user_view(request) :
    return render(request, 'searchmed/add_med_user.html', {})

def add_med_user(request) :
    return render(request, 'searchmed/add_med_user.html', {})

def check_medicine(request):
    product_name = request.GET.get('product_name')
    if product_name:
        medicines = Med.objects.filter(product_name__icontains=product_name)
    else:
        medicines = Med.objects.none()
    medicines_list = medicines.values('id', 'product_name', 'compound_name', 'compound_code', 'product_code', 'company_name')
    return JsonResponse({'medicines': list(medicines_list)})

def check_contraindication(request):
    medA_id = request.GET.get('medA_id')
    medB_id = request.GET.get('medB_id')
    if medA_id and medB_id:
        results = Medcontraindication.objects.filter(
            Q(med_id_a=medA_id, med_id_b=medB_id) | Q(med_id_a=medB_id, med_id_b=medA_id)
        )
    else:
        results = Medcontraindication.objects.none()
    
    data = []
    for r in results:
        data.append({
            'contraindicated_info': r.contraindicated_info,
            'notification_no': r.notification_no,
            'notification_date': r.notification_date.strftime('%Y-%m-%d'),
            'detail_info': r.detail_info
        })

    return JsonResponse(data, safe=False)

def signup_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)  # 선택적: 회원가입 후 자동 로그인
            return redirect('searchmed:home')  # 회원가입 후 이동할 페이지
    else:
        form = UserCreationForm()

    return render(request, 'searchmed/signup.html', {'form': form})

class CustomLoginView(LoginView):
    template_name = 'searchmed/login.html'

    def get_success_url(self):
        if self.request.user.is_superuser:
            return reverse_lazy('searchmed:addinfo')
        return reverse_lazy('searchmed:home')

@login_required
def addinfo_view(request):

    if not request.user.is_superuser:
        return HttpResponseForbidden("You don't have permission to access this page.")

    if request.method == 'GET':
        return render(request, 'searchmed/addinfo.html')

    elif request.method == 'POST':
        product_name = request.POST.get('product_name')
        compound_name = request.POST.get('compound_name')
        compound_code = request.POST.get('compound_code')
        product_code = request.POST.get('product_code')
        company_name = request.POST.get('company_name')

        med_db_lib.insert_into_med_db(product_name.encode('utf-8'), compound_name.encode('utf-8'), compound_code.encode('utf-8'), product_code.encode('utf-8'), company_name.encode('utf-8'))

        return redirect('searchmed:addinfo')
    
    else:
        return HttpResponse("Unsupported HTTP method.")
    
@login_required
def user_med_view(request):
    # 로그인 여부 확인 (옵션)
    if not request.user.is_authenticated:
        return redirect('searchmed:login')

    return render(request, 'searchmed/user_med.html')


def add_medicine(request):
    if request.method == 'POST':
        med_id =request.POST.get('med_id')
        med = Med.objects.get(id=med_id)

        medication_exists = UserMedication.objects.filter(
            user=request.user, 
            med=med
        ).exists()

        if medication_exists:
            return JsonResponse({
                'status': 'error', 
                'message': '이미 추가된 약품입니다. You have already added this medication.'
            }, status=400)

        UserMedication.objects.create(user=request.user, med=med)
        return JsonResponse({'status': 'success', 'message': 'Medication added successfully.'})
    
    # POST 요청이 아닌 경우 오류 메시지를 담은 JsonResponse를 반환합니다.
    return JsonResponse({'status': 'error', 'message': 'Invalid request'}, status=400)  
    

@login_required
def get_user_medications(request):
    user_medications = UserMedication.objects.filter(user=request.user).select_related('med')
    medications_list = [
        {
            'product_name': user_med.med.product_name,
            'compound_name': user_med.med.compound_name,
            'compound_code': user_med.med.compound_code,
            'product_code': user_med.med.product_code,
            'company_name': user_med.med.company_name,
            
        }
        for user_med in user_medications
    ]
    return JsonResponse({'medications': medications_list})

@login_required
def get_user_contraindications(request):
    user_medications = UserMedication.objects.filter(user=request.user).select_related('med')
    med_id_list = [
        {'id': user_med.med.id,
         'product_name': user_med.med.product_name,
        }
        for user_med in user_medications
    ]

    data = []
    for i in range(0, len(med_id_list)) :
        if (i < len(med_id_list) -1):
            for j in range (i+1, len(med_id_list)):
                medA_id = med_id_list[i]['id']
                medB_id = med_id_list[j]['id']
                results = Medcontraindication.objects.filter(
                    Q(med_id_a=medA_id, med_id_b=medB_id) | Q(med_id_a=medB_id, med_id_b=medA_id)
                    )
        
                for r in results:
                    data.append({
                        'med_a': med_id_list[i]['product_name'],
                        'med_b': med_id_list[j]['product_name'],
                        'contraindicated_info': r.contraindicated_info,
                        'notification_no': r.notification_no,
                        'notification_date': r.notification_date.strftime('%Y-%m-%d'),
                        'detail_info': r.detail_info
                    })

    return JsonResponse(data, safe=False)                 
                

searchmed/templates/searchmed/add_med_user.html
<!DOCTYPE html>
{% load static %}
<html lang="ko">
<head>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>병용금지 의약품 조회</title>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
    
    <div class="search-container">
        <header class ="search-header">
            Add Medications
        </header>

        <form method="POST">
            {% csrf_token %}
        <div class="input-group">
            <input type="text" placeholder="Medication Name" id="productA">
            <button class="search-btn" type="button" onclick="validateMedicine('productA')">🔍</button>
        </div>
        <div id="medicine-list" style="display:none;"></div>
        <div style="text-align: right;">
            <button class="search-btn disabled" type="button" id="addMedicineBtn" onclick="addMedicine()" disabled>Add</button>
        </div>
        <div id="resultsContainer"></div>
    </div>

    <script>
        let med_id = "";
        
        function validateMedicine(productId) {
            // checks if the medicine exists in med_db.med
            let inputVal = document.getElementById(productId).value;
            
            // AJAX 요청을 통해 의약품을 검증한다
            
            $.ajax({
                url: '/check_medicine/', // Django URL endpoint
                method: 'GET',
                data: {
                    'product_name' : inputVal
                },
                success: function(data) {

                    if (data.medicines && data.medicines.length > 0) {
                        displayMedicines(data.medicines, productId);
                    }
                },
                error: function(err) {
                    console.error("Error fetchig medicines", err);
                }
            });
        }

        function displayMedicines(medicines, productId) {
            let medicineListDiv = document.getElementById("medicine-list");
            medicineListDiv.innerHTML = ""; // Clear previous list

            // 테이블 헤더 생성
            let table = document.createElement("table");
            let header = document.createElement("tr");
            let headers = [
                "제품명 (product name)", 
                "성분명 (compound name)", 
                "성분코드 (compound code)", 
                "제품코드 (product code)", 
                "업체명 (company name)"
            ];
            headers.forEach(h => {
                let th = document.createElement("th");
                th.innerText = h;
                header.appendChild(th);
            });
            table.appendChild(header);


            medicines.forEach(med => {
                let tr = document.createElement("tr");
                let data = [
                    med.product_name,
                    med.compound_name,
                    med.compound_code,
                    med.product_code,
                    med.company_name
                ];
                data.forEach(d => {
                    let td = document.createElement("td");
                    td.innerText = d;
                    tr.appendChild(td);
                });

                // 클릭 이벤트 추가
                tr.onclick = function() {
                    if (productId === 'productA') {
                        med_id = med.id;
                    } 

                    // 사용자의 입력 상자에 선택한 의약품 이름을 설정합니다
                    document.getElementById(productId).value = med.product_name;
                    
                    // 목록을 숨깁니다
                    medicineListDiv.style.display = "none";

                    if (med_id) {
                        document.getElementById('addMedicineBtn').classList.remove('disabled');
                        document.getElementById('addMedicineBtn').disabled = false;
                    }
                };
                table.appendChild(tr);
            });
            medicineListDiv.appendChild(table);
            medicineListDiv.style.display = "block";
        }

        function addMedicine() {
            var csrfToken = document.querySelector('[name=csrfmiddlewaretoken]').value;
            $.ajax({
                url: '/add_medicine/', 
                type: 'POST',
                data: {
                    'med_id':med_id,
                    'csrfmiddlewaretoken':csrfToken
                },
                success: function(response) {
                    alert("The medication has been successfully added.");
                },
                error: function(error) {
                    alert("An error occurred: " +xhr.status + " " + error);
                }
            })
        }

    </script>
</body>
</html>

searchmed/templates/searchmed/addinfo.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>정보 추가 Add Info</title>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <style>
        form {
            display: flex;
            flex-direction: column;
            align-items: center;
            justify-content: center;
            margin: 0 auto;
            font-size: 16px;
        }

        button[type="submit"] {
            font-size: 14px;
            margin-top: 20px;
            background-color: white;
            border-radius: 10%;
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.2);
        }
    </style>
</head>
<body>
    <h1>Add Product Information</h1>

    <form method="POST">
        {% csrf_token %}
        <div class="form-container">
            <label for="product_name">제품명 Product Name:</label><br>
            <input type="text" id="product_name" name="product_name" required><br><br>

            <label for="compound_name">성분명 Compound Name:</label><br>
            <input type="text" id="compound_name" name="compound_name" required><br><br>

            <label for="compound_code">성분코드 Compound Code:</label><br>
            <input type="text" id="compound_code" name="compound_code" required><br><br>

            <label for="product_code">제품코드 Product Code:</label><br>
            <input type="text" id="product_code" name="product_code" required><br><br>

            <label for="company_name">업체명 Company Name:</label><br>
            <input type="text" id="company_name" name="company_name" required><br><br>

            <input type="submit" value="추가 Add">
        </div>
    </form>
</body>
</html>

searchmed/templates/searchmed/combine.html
<!DOCTYPE html>
{% load static %}
<html lang="ko">
<head>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>병용금지 의약품 조회</title>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <style>
        .search-container {
        background-color: #fff;
        padding: 30px;
        padding-bottom: 25px;
        border-radius: 8px;
        box-shadow: 0 4px 12px rgba(0,0,0,0.1);
        width: 100%;
        max-width: 1200px;  /* 최대 너비 설정 */
        box-sizing: border-box;
        margin: auto;
    }
    </style>
</head>
<body>
    
    <div class="search-container">
        <header class ="search-header">
            병용금지 의약품 확인 Check Medication Compatability
        </header>

        <form method="POST">
            {% csrf_token %}
        <div class="input-group">
            <input type="text" placeholder="첫 번째 약의 이름을 입력하세요 type the 1st medication name" id="productA" autocomplete="off">
            <button class="search-btn" type="button" onclick="validateMedicine('productA')">🔍</button>
        </div>
        <div id="medicine-list" style="display:none;"></div>
        <div class="input-group">
            <input type="text" placeholder="두 번째 약의 이름을 입력하세요 type the 2nd medication name" id="productB" autocomplete="off">
            <button class="search-btn" type="button" onclick="validateMedicine('productB')">🔍</button>
        </div>
        <div style="text-align: right;">
            <button class="search-btn disabled" type="button" id="combinedSearchBtn" onclick="searchCombined()" disabled>검색 Search</button>
        </div>
        <div id="resultsContainer"></div>
    </div>

    <script>
        let medA_id = "";
        let medB_id = "";

        function validateMedicine(productId) {
            // checks if the medicine exists in med_db.med
            let inputVal = document.getElementById(productId).value;
            
            // AJAX 요청을 통해 의약품을 검증한다
            
            $.ajax({
                url: '/check_medicine/', // Django URL endpoint
                method: 'GET',
                data: {
                    'product_name' : inputVal
                },
                success: function(data) {

                    if (data.medicines && data.medicines.length > 0) {
                        displayMedicines(data.medicines, productId);
                    }
                },
                error: function(err) {
                    console.error("Error fetchig medicines", err);
                }
            });
        }

        function displayMedicines(medicines, productId) {
            let medicineListDiv = document.getElementById("medicine-list");
            medicineListDiv.innerHTML = ""; // Clear previous list

            // 테이블 헤더 생성
            let table = document.createElement("table");
            let header = document.createElement("tr");
            let headers = [
                "제품명 (product name)", 
                "성분명 (compound name)", 
                "성분코드 (compound code)", 
                "제품코드 (product code)", 
                "업체명 (company name)"
            ];
            headers.forEach(h => {
                let th = document.createElement("th");
                th.innerText = h;
                header.appendChild(th);
            });
            table.appendChild(header);


            medicines.forEach(med => {
                let tr = document.createElement("tr");
                let data = [
                    med.product_name,
                    med.compound_name,
                    med.compound_code,
                    med.product_code,
                    med.company_name
                ];
                data.forEach(d => {
                    let td = document.createElement("td");
                    td.innerText = d;
                    tr.appendChild(td);
                });

                // 클릭 이벤트 추가
                tr.onclick = function() {
                    if (productId === 'productA') {
                        medA_id = med.id;

                    } else if (productId === 'productB') {
                        medB_id = med.id;
                    }

                    // 사용자의 입력 상자에 선택한 의약품 이름을 설정합니다
                    document.getElementById(productId).value = med.product_name;
                    
                    // 목록을 숨깁니다
                    medicineListDiv.style.display = "none";

                    if (medA_id && medB_id) {
                        document.getElementById('combinedSearchBtn').classList.remove('disabled');
                        document.getElementById('combinedSearchBtn').disabled = false;
                    }
                };
                table.appendChild(tr);
            });
            medicineListDiv.appendChild(table);
            medicineListDiv.style.display = "block";
        }

        function searchCombined() {
            // 제품명 A와 B가 모두 검증되면 이 함수에서 병용금지 조회를 실행하실 수 있습니다.
            $.ajax({
                url: '/check_contraindication/',
                method: 'GET',
                data: {
                    'medA_id' : medA_id,
                    'medB_id' : medB_id
                },
                success: function(data) {
                    if (data && data.length > 0) {
                        var tableHTML = '<table id="resultTable">';
                        tableHTML += '<thead><tr><th>상세정보 (contraindicated_info)</th><th>고시번호 (notification_no)</th><th>고시일자 (notification_date)</th><th>비고 (detail_info)</th></tr></thead>';
                        tableHTML += '<tbody>';
                        for (var i = 0; i < data.length; i++) {
                            tableHTML += '<tr>';
                            tableHTML += '<td>' + data[i].contraindicated_info + '</td>';
                            tableHTML += '<td>' + data[i].notification_no + '</td>';
                            tableHTML += '<td>' + data[i].notification_date + '</td>';
                            tableHTML += '<td>' + data[i].detail_info + '</td>';
                            tableHTML += '</tr>';
                        }
                        tableHTML += '</tbody>';
                        tableHTML += '</table>';

                        document.getElementById('resultsContainer').innerHTML = tableHTML; 
                    } else {
                        document.getElementById('resultsContainer').innerHTML = '병용금지 약품 조합이 아닙니다. (This is not a combination for contraindicated medications.)';
                    }
                },
                error: function(err) {
                    console.error("Error fetching contraindication info", err);
                }
            });
        }
    </script>
</body>
</html>

searchmed/templates/searchmed/home.html
<!DOCTYPE html>
{% load static %}
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>홈 화면 Home Page</title>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <style>
        p1{
            color: #007BFF;
            text-align: center;
            font-size: 1.5em;
        }
        .button-group {
            display: flex;
            flex-direction: column;
            gap: 20px;
            text-align: center;
        }
        button {
            padding: 15px 30px;
            font-size: 1.5em;
            cursor: pointer;
            border: none;
            border-radius: 5px;
            background-color: #007BFF;
            color: #ffffff;
            transition: background-color 0.3s;
            text-align: center;
        }
        button:hover {
            background-color: #0056b3;
        }
    </style>
</head>
<body>
    <div class="button-group">
        <h1>NOVERDOSE</h1>
        {% if request.user.is_authenticated %}
            <p1>Welcome, {{request.user.get_username}}!</p1>
        {% endif %}
        <a href="{% url 'searchmed:combine' %}"><button>병용금기 의약품 Contraindications for Combined Usage</button>
        
        {% if request.user.is_authenticated %}
            {% if not request.user.is_superuser %}
                <a href="{% url 'searchmed:user_med' %}"><button>의약품 등록 Register Your Medications</button>
            {% endif %}
            <a href="{% url 'searchmed:logout' %}"><button>로그아웃 Logout</button></a>
        {% else %}
            <a href="{% url 'login' %}"><button>관리자 로그인 및 정보 추가 Admin Login and Adding Info</button></a>
            <a href="{% url 'login' %}"><button>일반 사용자 로그인 Normal User Login</button></a>
            <a href="{% url 'searchmed:signup' %}"><button>사용자 등록 User Registration</button></a>
        {% endif %}
    </div>
</body>
</html>

searchmed/templates/searchmed/log.html
<!DOCTYPE html>
{% load static %}
<html lang="ko">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Searched drugs log</title>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
    <div class="search-container">
        <header class ="search-header">
            View Searched Drugs Log
        </header>

        <form method="POST" id="logForm">
            {% csrf_token %}
        <div class="input-group">
            <input type="text" placeholder="type the log's id" id="logId">
            <button class="search-btn" type="button" onclick="getLog()">🔍</button>
        </div>
        <div id="logResult"></div>
    </div>
        
    <script>
        function getLog() {
            var logId = document.getElementById('logId').value;
            var formData = new FormData();
            formData.append('log_id', logId);

            fetch('/display_log/', {
                method: 'POST',
                body: formData,
                // {% csrf_token %}
            })
            .then(response => response.text())
            .then(data => {
                document.getElementById('logResult').innerText = data;
            });
        }
    </script>
</body>

searchmed/templates/searchmed/login.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <title>로그인 화면 Login Page</title>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <style>
        form {
            display: flex;
            flex-direction: column;
            align-items: center;
            justify-content: center;
            margin: 0 auto;
            font-size: 16px;
        }

        button[type="submit"] {
            font-size: 14px;
            margin-top: 20px;
            background-color: white;
            border-radius: 10%;
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.2);
        }
        .errorlist {
            margin-top: 15px;
            list-style-type: none;
            color: rgb(168, 0, 0);
            font-size: 10px;
        }
    </style>
</head>
<body>
    <h1>Login</h1>

    <form method="post">
        {% csrf_token %}
        <div class="form-container">
            <div>
                <label for="id_username">사용자명 Username:</label>
                <input type="text" name="username" required id="id_username" autocomplete="off">
            </div>
            <div>
                <label for="id_password">비밀번호 Password:</label>
                <input type="password" name="password" required id="id_password" autocomplete="off">
            </div>
            <div>
                <button type="submit">로그인 Login</button>
            </div>
            {% if form.non_field_errors %}
                <div class="errorlist">{{ form.non_field_errors }}</div>
            {% endif %}
        </div>
    </form>
</body>
</html>

searchmed/templates/searchmed/signup.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <title>등록 화면 Registration Page</title>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <style>
        .tooltip-container {
            position: relative;
            display: inline-block;
        }
        
        .help-button {
            margin-left: 10px;
            cursor: pointer;
            border: transparent;
            background-color: transparent;
            width: 20px;
            height: 20px;
            display: flex;
            justify-content: center;
            align-items: center;
            font-size: 16px;
            color: white;
        }

        .input-group {
            margin-bottom: 10px; 
        }

        .field-container {
            display: flex;
            align-items: center;
        }

        .tooltip-text {
            font-size: 10px;
            visibility: hidden;
            width: 320px;
            background-color: white;
            color: green;
            text-align: left;
            position: absolute;
            left: 70%;
            z-index: 1;
            opacity: 0;
            transition: opacity 0.5s;
        }
        
        .tooltip-container .help-button:hover + .tooltip-text, .help-button:hover + .tooltip-text {
            visibility: visible;
            opacity: 0.85;
        }
    
        form {
            display: flex;
            flex-direction: column;
            align-items: center;
            justify-content: center;
            margin: 0 auto;
            font-size: 16px;
        }

        .errorlist {
            margin-top: 10px;
            list-style-type: none;
            color: rgb(168, 0, 0);
            font-size: 10px;
        }
    </style>
</head>
<body>
    <h1>Registration</h1>

    <form method="post">
        {% csrf_token %}
        <div class="form-container">
            <div class="input-group">
                <label for="{{ form.username.id_for_label }}">사용자명 Username: </label>
                <div class="field-container">
                    {{ form.username }}
                    <button type="button" class="help-button">ⓘ</button>
                    <span class="tooltip-text">{{ form.username.help_text }}</span>
                </div>
            </div>
            <div class="input-group">
                <label for="{{ form.password1.id_for_label }}">비밀번호 Password: </label>
                <div class="field-container">
                    {{ form.password1 }}
                    <button type="button" class="help-button">ⓘ</button>
                    <span class="tooltip-text">{{ form.password1.help_text }}</span>
                </div>
            </div>
            <div class="input-group">
                <label for="{{ form.password2.id_for_label }}">비밀번호 확인하기 Confirm Password: </label>
                {{ form.password2 }}
            </div>
            <button type="submit">등록하기 Register</button>

            {% if form.username.errors %}
            <div class="errorlist">{{ form.username.errors.as_text }}</div>
            {% endif %}
            {% if form.password1.errors %}
            <div class="errorlist">{{ form.password1.errors.as_text }}</div>
            {% endif %}
            {% if form.password2.errors %}
            <div class="errorlist">{{ form.password2.errors.as_text }}</div>
            {% endif %}
        </div>
    </form>
</body>

</html>